---
include:
#  - board: eyelash_corne_left
#    shield: nice_view
#    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: nice_view_adapter nice_view
    artifact-name: right_eyelash_corne
    #snippet: zmk-usb-logging
  - board: eyelash_corne_left
    shield: nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    artifact-name: left_eyelash_corne
  - board: reset_eyelash_core
    shield: settings_reset
    #snippet: zmk-usb-logging
